include::entities.adoc[]
:isofile: SLE-15-SP1-Installer-DVD-x86_64-Build225.1-Media1.iso
:isolink: http://download.suse.de/install/SLE-15-SP1-Installer-GMC1/

== Deployment on VMWare

=== Environment description

[IMPORTANT]
====
These instructions currently do not describe how to set up a load balancer.
This will be added in future versions. You must provide your own load balancing
solution that directs access to the master nodes.
====

[NOTE]
====
The {ay} file generated by skuba is a template. It has the base requirements.
This {ay} file should act as a guide and should be updated with your companies standards.
====


=== {ay} preparation

. Generate {ay} template file using
+
----
skuba infra autoyast
----
. Update the {ay} file with your registration keys and company best practices.
. Host the {ay} file on a webserver reachable inside the network you will be setting up skuba in
. Add autoyast=https://[webserver/path/to/autoyast.xml] to your sles15 SP1 install

==== {sls} installation

[NOTE]
====
Use AutoYaST and ensure to use a staged frozen patchlevel via SMT/SUSE Manager to ensure 100% reproducible setup.
====

Once the machines have been installed using the autoyast file, you are now ready to boostrap your cluster
link:deployment-bootstrap.adoc[bootstrap guide]
